(function () {
  "use strict";

  // Reads window.SITE_PROJECTS / window.SITE_ARCHIVE (from data/projects.js
  // and data/archive.js, generated by scripts/sync-content.mjs) and fills
  // the page. Must run after those two data files and before script.js —
  // see the <script> order in index.html.
  //
  // Two different jobs, one per project tier:
  //  - Archive/secondary projects: the whole <button class="depth-card">
  //    markup is generated from data (see archiveCard()).
  //  - Primary projects: the bespoke HTML for each big section stays
  //    hand-authored in index.html (that composition is the point of the
  //    design and isn't templated) — this only fills the leaf text/src/alt
  //    values marked with data-field / data-media, so the same content
  //    doesn't need to be hand-typed in the index list AND the panel.

  function esc(value) {
    return String(value ?? "").replace(/[&<>"']/g, (ch) => (
      { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[ch]
    ));
  }

  // --- Archive tier: full generation ---
  function archiveCard(project, index) {
    return `<button class="depth-card" type="button" data-index="${index}" data-slug="${esc(project.slug)}" data-number="${esc(project.number)}" data-title="${esc(project.title)}" data-type="${esc(project.type)}" data-position="0" aria-pressed="${index === 0 ? "true" : "false"}">
      <figure><img src="${esc(project.image)}" alt="${esc(project.alt)}" width="1000" height="1200" loading="lazy"><figcaption class="media-caption"><span>${esc(project.number)}</span><strong>${esc(project.title)}</strong></figcaption></figure>
    </button>`;
  }

  document.querySelectorAll('[data-render="archive-cards"]').forEach((el) => {
    const projects = window.SITE_ARCHIVE || [];
    el.innerHTML = projects.map(archiveCard).join("");
  });

  // --- Primary tier: fill data-field / data-media markers in place ---
  const projectsBySlug = {};
  (window.SITE_PROJECTS || []).forEach((project) => {
    projectsBySlug[project.slug] = project;
  });

  document.querySelectorAll("[data-field]").forEach((el) => {
    const [slug, field] = String(el.dataset.field).split(".");
    const project = projectsBySlug[slug];
    if (!project || !(field in project)) return;
    const value = project[field];
    const target = el.dataset.fieldTarget;
    if (target) {
      el.setAttribute(target, value);
    } else {
      el.textContent = value;
    }
  });

  const mediaByKey = {};
  (window.SITE_PROJECTS || []).forEach((project) => {
    (project.media || []).forEach((media) => {
      mediaByKey[`${project.slug}.${media.slot}`] = media;
    });
  });

  document.querySelectorAll("[data-media]").forEach((el) => {
    const media = mediaByKey[String(el.dataset.media)];
    if (!media) return;
    if (el.tagName === "IMG") {
      el.src = media.image;
      el.alt = media.alt;
      return;
    }
    const target = el.dataset.mediaTarget;
    if (target === "number") el.textContent = media.captionNumber;
    else if (target === "label") el.textContent = media.captionLabel;
  });
})();
