(function () {
  "use strict";

  // Reads window.SITE_PROJECTS / window.SITE_ARCHIVE (from data/projects.js
  // and data/archive.js, generated by scripts/sync-content.mjs) and fills
  // the page. Must run after those two data files and before script.js —
  // see the <script> order in index.html.
  //
  // Two different jobs, one per project tier:
  //  - Archive/secondary projects: the whole <button class="depth-card">
  //    markup is generated from data (see archiveCard()).
  //  - Primary projects: the bespoke HTML for each big section stays
  //    hand-authored in index.html (that composition is the point of the
  //    design and isn't templated) — this only fills the leaf text/src/alt
  //    values marked with data-field / data-media, so the same content
  //    doesn't need to be hand-typed in the index list AND the panel.

  function esc(value) {
    return String(value ?? "").replace(/[&<>"']/g, (ch) => (
      { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[ch]
    ));
  }

  // --- Responsive image sources (rules/images.md: AVIF + WebP, 640/960/
  // 1536 widths, never upscaled — see scripts/optimize-images.mjs, which
  // generates the files this reads from data/image-variants.js). ---
  const imageVariants = window.SITE_IMAGE_VARIANTS || {};

  function buildSrcset(basePath, format) {
    const widths = imageVariants[basePath];
    if (!widths || !widths.length) return "";
    const withoutExt = basePath.replace(/\.\w+$/, "");
    return widths.map((w) => `${withoutExt}-${w}.${format} ${w}w`).join(", ");
  }

  function pictureSourcesMarkup(basePath, sizes) {
    const avif = buildSrcset(basePath, "avif");
    const webp = buildSrcset(basePath, "webp");
    const sizesAttr = esc(sizes);
    return `${avif ? `<source type="image/avif" srcset="${esc(avif)}" sizes="${sizesAttr}">` : ""}${webp ? `<source type="image/webp" srcset="${esc(webp)}" sizes="${sizesAttr}">` : ""}`;
  }

  // Applies to an existing <img> that already sits inside a <picture> in
  // the HTML (used for data-field/data-media-driven images, whose <img>
  // src changes at runtime — see below).
  function applyPictureSources(imgEl, basePath) {
    const picture = imgEl.closest("picture");
    if (!picture) return;
    const avifSource = picture.querySelector('source[type="image/avif"]');
    const webpSource = picture.querySelector('source[type="image/webp"]');
    const avifSrcset = buildSrcset(basePath, "avif");
    const webpSrcset = buildSrcset(basePath, "webp");
    if (avifSource) avifSource.srcset = avifSrcset;
    if (webpSource) webpSource.srcset = webpSrcset;
  }

  // --- Archive tier: full generation ---
  function archiveCard(project, index) {
    const sizes = "(min-width: 900px) 30vw, 78vw";
    return `<button class="depth-card" type="button" data-index="${index}" data-slug="${esc(project.slug)}" data-number="${esc(project.number)}" data-title="${esc(project.title)}" data-type="${esc(project.type)}" data-position="0" aria-pressed="${index === 0 ? "true" : "false"}">
      <figure><picture>${pictureSourcesMarkup(project.image, sizes)}<img src="${esc(project.image)}" alt="${esc(project.alt)}" width="1000" height="1200" loading="lazy" decoding="async"></picture><figcaption class="media-caption"><span>${esc(project.number)}</span><strong>${esc(project.title)}</strong></figcaption></figure>
    </button>`;
  }

  document.querySelectorAll('[data-render="archive-cards"]').forEach((el) => {
    const projects = window.SITE_ARCHIVE || [];
    el.innerHTML = projects.map(archiveCard).join("");
  });

  // --- Primary tier: fill data-field / data-media markers in place ---
  const projectsBySlug = {};
  (window.SITE_PROJECTS || []).forEach((project) => {
    projectsBySlug[project.slug] = project;
  });

  document.querySelectorAll("[data-field]").forEach((el) => {
    const [slug, field] = String(el.dataset.field).split(".");
    const project = projectsBySlug[slug];
    if (!project || !(field in project)) return;
    const value = project[field];
    const target = el.dataset.fieldTarget;
    if (target) {
      el.setAttribute(target, value);
      if (target === "src" && el.tagName === "IMG") applyPictureSources(el, value);
    } else {
      el.textContent = value;
      // h2Middle ("dans les" on cabane) is empty for every other project —
      // hide the element rather than leave a stray blank line.
      if (field === "h2Middle") el.hidden = !value;
    }
  });

  // Keyed by slot AND stage, not just slot — cabane/nike/cave each have a
  // second "stage 2" media set that replaces the first on scroll (see
  // script.js's initStageCrossfade), reusing the same slot names.
  const mediaByKey = {};
  (window.SITE_PROJECTS || []).forEach((project) => {
    (project.media || []).forEach((media) => {
      mediaByKey[`${project.slug}.${media.slot}.${media.stage}`] = media;
    });
  });

  document.querySelectorAll("[data-media]").forEach((el) => {
    const media = mediaByKey[String(el.dataset.media)];
    if (!media) return;
    if (el.tagName === "IMG") {
      el.src = media.image;
      el.alt = media.alt;
      applyPictureSources(el, media.image);
      return;
    }
    const target = el.dataset.mediaTarget;
    if (target === "number") el.textContent = media.captionNumber;
    else if (target === "label") el.textContent = media.captionLabel;
  });
})();
